MERGE INTO USERS (ID, USERNAME, PASSWORD, ROLE)
KEY(USERNAME)
VALUES (1, 'admin', '$2a$10$5rBfszKHMTcfNPVoO7Cw9uM1QxjK1J1cAzTxOjTi4QoQ7GfNbnHF6', 'ADMIN');

MERGE INTO USERS (ID, USERNAME, PASSWORD, ROLE)
KEY(USERNAME)
VALUES (2, 'user', '$2a$10$uQuz8W2sgAyat1QxR3K6HeRYC8/UOrkF7zTyX/Ydt9s0xTcVNHhOq', 'USER');
