-- ID 생략
INSERT INTO USERS (USERNAME, PASSWORD, ROLE)
VALUES ('admin', '$2a$10$5rBfszKHMTcfNPVoO7Cw9uM1QxjK1J1cAzTxOjTi4QoQ7GfNbnHF6', 'ADMIN');

INSERT INTO USERS (USERNAME, PASSWORD, ROLE)
VALUES ('user', '$2a$10$uQuz8W2sgAyat1QxR3K6HeRYC8/UOrkF7zTyX/Ydt9s0xTcVNHhOq', 'USER');
