CREATE TABLE IF NOT EXISTS USERS (
  ID BIGINT PRIMARY KEY,
  USERNAME VARCHAR(255) UNIQUE,
  PASSWORD VARCHAR(255),
  ROLE VARCHAR(50),
  FACE_REGISTERED BOOLEAN DEFAULT FALSE -- 👈 여기로 통합 가능
);
CREATE SEQUENCE IF NOT EXISTS SEQ_USERS START WITH 1;

-- ❌ 중복이므로 제거하세요
-- ALTER TABLE USERS ADD FACE_REGISTERED BOOLEAN DEFAULT FALSE;
