-- schema.sql
CREATE SEQUENCE IF NOT EXISTS SEQ_USERS START WITH 1;

CREATE TABLE IF NOT EXISTS USERS (
  ID BIGINT PRIMARY KEY DEFAULT NEXT VALUE FOR SEQ_USERS,
  USERNAME VARCHAR(255) UNIQUE,
  PASSWORD VARCHAR(255),
  ROLE VARCHAR(50)
);
